FROM ros:noetic

##### GPG keys fix
RUN rm /etc/apt/sources.list.d/ros1-latest.list \
  && rm /usr/share/keyrings/ros1-latest-archive-keyring.gpg

RUN apt-get update \
  && apt-get install -y ca-certificates curl

RUN export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}') ;\
    curl -L -s -o /tmp/ros-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo $VERSION_CODENAME)_all.deb" \
    && apt-get update \
    && apt-get install /tmp/ros-apt-source.deb \
    && rm -f /tmp/ros-apt-source.deb
####################

RUN apt update && apt install -y rviz \
         ros-noetic-moveit \
         curl \
         apt-utils \
         python3-pip \
         python-is-python3 \
         net-tools \
         nmap \
         xauth \
         ros-noetic-robot-state-publisher \
         ros-noetic-joint-state-publisher \
         git \
         ros-noetic-usb-cam \
         htop \
         sudo \
         libxmlrpc-core-c3-dev

RUN pip install catkin_tools \
                tensorboard \
                ur_rtde

RUN rm -rf /var/lib/apt/lists/* && \
    groupadd -g 1000 laboratorio && \
    useradd -ms /bin/bash laboratorio -u 1000 -g 1000 && \
    echo "laboratorio ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    echo "source /opt/ros/noetic/setup.bash" >> /home/laboratorio/.bashrc && \
    RUN echo 'laboratorio:laboratorio' | chpasswd && \
    chown laboratorio:laboratorio /home/laboratorio && \
    mkdir -p /var/run/laboratorio/1000 && \
    chown laboratorio:laboratorio /var/run/laboratorio/1000

USER laboratorio

ENTRYPOINT [ "sleep", "infinity"]